#!/usr/bin/env python3
"""Generate an offline country -> major-city catalogue from GeoNames."""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
import unicodedata
import zipfile


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "lib/StarScopeCore/src/generated_city_data.cpp"


@dataclass(frozen=True)
class City:
    name: str
    latitude: float
    longitude: float
    country: str
    population: int
    feature: str
    timezone: str


def ascii_text(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    return normalized.encode("ascii", "ignore").decode("ascii").strip()


def c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def countries(path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if line.startswith("#") or not line.strip():
                continue
            fields = line.rstrip("\n").split("\t")
            result[fields[0]] = ascii_text(fields[4])
    return result


def timezone_offsets(path: Path) -> dict[str, tuple[int, int]]:
    result: dict[str, tuple[int, int]] = {}
    with path.open(encoding="utf-8") as handle:
        reader = csv.reader(handle, delimiter="\t")
        next(reader, None)
        for fields in reader:
            if len(fields) < 5:
                continue
            try:
                standard = round(float(fields[4]) * 60)
                daylight = round(float(fields[3]) * 60)
            except ValueError:
                continue
            result[fields[1]] = (standard, daylight)
    return result


def read_cities(path: Path) -> list[City]:
    result: list[City] = []
    with zipfile.ZipFile(path) as archive:
        filename = next(name for name in archive.namelist() if name.endswith(".txt"))
        with archive.open(filename) as raw:
            for binary_line in raw:
                fields = binary_line.decode("utf-8").rstrip("\n").split("\t")
                if len(fields) < 19:
                    continue
                result.append(City(
                    name=ascii_text(fields[2] or fields[1]),
                    latitude=float(fields[4]),
                    longitude=float(fields[5]),
                    country=fields[8],
                    population=int(fields[14] or 0),
                    feature=fields[7],
                    timezone=fields[17],
                ))
    return result


def select_cities(all_cities: list[City]) -> dict[str, list[City]]:
    grouped: dict[str, list[City]] = {}
    for city in all_cities:
        grouped.setdefault(city.country, []).append(city)

    selected: dict[str, list[City]] = {}
    for code, items in grouped.items():
        items.sort(key=lambda city: city.population, reverse=True)
        top_count = 50 if code == "JP" else 8
        keep = {
            city for index, city in enumerate(items)
            if index < top_count or city.population >= 500_000
            or city.feature == "PPLC"
        }
        selected[code] = sorted(keep, key=lambda city: city.name.casefold())
    return selected


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("cities_zip", type=Path)
    parser.add_argument("country_info", type=Path)
    parser.add_argument("timezones", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    country_names = countries(args.country_info)
    offsets = timezone_offsets(args.timezones)
    selected = select_cities(read_cities(args.cities_zip))

    pool = bytearray()
    pool_offsets: dict[str, int] = {}

    def intern(text: str) -> int:
        if text not in pool_offsets:
            pool_offsets[text] = len(pool)
            pool.extend(text.encode("ascii"))
            pool.append(0)
        return pool_offsets[text]

    city_rows: list[tuple[int, int, int, int, int]] = []
    country_rows: list[tuple[str, int, int, int]] = []
    for code in sorted(selected, key=lambda value: country_names.get(value, value)):
        cities = selected[code]
        if not cities:
            continue
        first = len(city_rows)
        for city in cities:
            standard, daylight = offsets.get(city.timezone, (0, 0))
            city_rows.append((round(city.latitude * 100000),
                              round(city.longitude * 100000), intern(city.name),
                              standard, daylight))
        country_rows.append((code, intern(country_names.get(code, code)), first,
                             len(cities)))

    lines = [
        '// Generated by tools/build_city_catalog.py from GeoNames.\n',
        '#include "starscope/city_catalog.hpp"\n\n',
        'namespace starscope {\n\n',
        'const PackedCity kPackedCities[] = {\n',
    ]
    lines.extend(
        f"  {{{lat}, {lon}, {name}U, {standard}, {daylight}}},\n"
        for lat, lon, name, standard, daylight in city_rows
    )
    lines.extend([
        '};\n',
        'const std::size_t kPackedCityCount = '
        'sizeof(kPackedCities) / sizeof(kPackedCities[0]);\n\n',
        'const PackedCountry kPackedCountries[] = {\n',
    ])
    lines.extend(
        f'  {{"{code}", {name}U, {first}, {count}}},\n'
        for code, name, first, count in country_rows
    )
    lines.extend([
        '};\n',
        'const std::size_t kPackedCountryCount = '
        'sizeof(kPackedCountries) / sizeof(kPackedCountries[0]);\n\n',
        'const char kPlaceNamePool[] =\n',
    ])
    for value in pool_offsets:
        lines.append(f'  "{c_string(value)}\\0"\n')
    lines.extend([';\n\n', '}  // namespace starscope\n'])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("".join(lines), encoding="utf-8")
    print(f"generated {len(country_rows)} countries, {len(city_rows)} cities, "
          f"{len(pool)} name bytes -> {args.output}")


if __name__ == "__main__":
    main()

