#!/usr/bin/env python3
"""Generate the offline C++ fixed-star catalogue from HYG 4.1."""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
import unicodedata


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "lib/StarScopeCore/src/generated_star_data.cpp"


def ascii_text(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    return normalized.encode("ascii", "ignore").decode("ascii").strip()


def c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def choose_name(row: dict[str, str]) -> str:
    proper = ascii_text(row.get("proper", ""))
    if proper:
        return proper
    designation = ascii_text(row.get("bf", ""))
    return designation.replace(" ", "") if designation else ""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("csv", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--limit", type=float, default=6.5)
    args = parser.parse_args()

    stars: list[tuple[float, float, float, float, int, str]] = []
    with args.csv.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            name = choose_name(row)
            # HYG includes the Sun as a fixed RA=0/Dec=0 catalogue row. Its
            # real position is time-dependent and is calculated at runtime.
            if name == "Sol":
                continue
            try:
                magnitude = float(row["mag"])
                ra_deg = float(row["ra"]) * 15.0
                dec_deg = float(row["dec"])
            except (KeyError, TypeError, ValueError):
                continue
            if magnitude > args.limit or not math.isfinite(magnitude):
                continue
            try:
                color_index = float(row.get("ci") or 0.65)
            except ValueError:
                color_index = 0.65
            try:
                hip_id = int(row.get("hip") or 0)
            except ValueError:
                hip_id = 0
            stars.append((magnitude, ra_deg, dec_deg, color_index, hip_id, name))

    stars.sort(key=lambda item: (item[0], item[4]))
    offsets: dict[str, int] = {}
    name_pool = bytearray()
    encoded: list[tuple[int, int, int, int, int, int]] = []
    for magnitude, ra, dec, bv, hip, name in stars:
        if name:
            if name not in offsets:
                offsets[name] = len(name_pool)
                name_pool.extend(name.encode("ascii"))
                name_pool.append(0)
            name_offset = offsets[name]
        else:
            name_offset = 0xFFFFFFFF
        encoded.append((round(ra * 1000), round(dec * 1000),
                        round(magnitude * 100), round(bv * 1000), hip,
                        name_offset))

    lines = [
        '// Generated by tools/build_star_catalog.py from HYG 4.1.\n',
        '#include "starscope/star_catalog.hpp"\n\n',
        'namespace starscope {\n\n',
        'const PackedStar kPackedStars[] = {\n',
    ]
    lines.extend(
        f"  {{{ra}U, {dec}, {mag}, {bv}, {hip}U, {offset}U}},\n"
        for ra, dec, mag, bv, hip, offset in encoded
    )
    lines.extend([
        '};\n',
        'const std::size_t kPackedStarCount = '
        'sizeof(kPackedStars) / sizeof(kPackedStars[0]);\n\n',
        'const char kStarNamePool[] =\n',
    ])
    for name in offsets:
        lines.append(f'  "{c_string(name)}\\0"\n')
    if not offsets:
        lines.append('  "\\0"\n')
    lines.extend([';\n\n', '}  // namespace starscope\n'])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("".join(lines), encoding="utf-8")
    print(f"generated {len(encoded)} stars, {len(name_pool)} name bytes -> {args.output}")


if __name__ == "__main__":
    main()
